


"""
Django settings for geodjango_assignment project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [BASE_DIR / "static"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', ]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Application definition
INSTALLED_APPS = [
    'leaflet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'world',
    'django.contrib.contenttypes',
    'whitenoise',
    'profiles',
    'crispy_forms',
    'geocoder',
    'fixtures',
    'club',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'geodjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geodjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# new database
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'backend',
        'USER': 'backend',
        'PASSWORD': 'backend1',
        'HOST': 'gis.cxi4a2wi8o0l.eu-west-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}
#  old database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'gis',
#         'USER': 'docker',
#         'PASSWORD': 'docker',
#         'PORT': 25432,  # Adjusted to the mapped port
#     },
# }

# import socket

# LOCAL_DOCKER_TEST = False
# DEPLOY_SECURE = True

# if LOCAL_DOCKER_TEST:
#     DATABASES["default"]["HOST"] = "geodjango-assignment-postgis"
#     DATABASES["default"]["PORT"] = 5432
# elif socket.gethostname() == "SHANES-WORKSTATION":
#     DATABASES["default"]["HOST"] = "localhost"
#     DATABASES["default"]["PORT"] = 25432
# else:
#     DATABASES["default"]["HOST"] = "geodjango-assignment-postgis"
#     DATABASES["default"]["PORT"] = 5432
#     DEPLOY_SECURE = True

# # Set DEPLOY_SECURE to True only for LIVE deployment
# if DEPLOY_SECURE:f
#     DEBUG = False
#     TEMPLATES[0]["OPTIONS"]["debug"] = False
#     ALLOWED_HOSTS = ['*', ]
#     CSRF_COOKIE_SECURE = True
#     SESSION_COOKIE_SECURE = True
# else:
#     DEBUG = True
#     TEMPLATES[0]["OPTIONS"]["debug"] = True
#     ALLOWED_HOSTS = ['*', ]
#     CSRF_COOKIE_SECURE = False
#     SESSION_COOKIE_SECURE = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (53.377651874950075, -7.478513691999692),
    'DEFAULT_ZOOM': 18,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'RESET_VIEW': False,
    'SCALE': None,
    'OPACITY': 0.5,
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://http://caoimhemccann.xyz/', 'http://www.caoimhemccann.xyz/'
]

# PWA SETTINGS
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/assets/js', 'ServiceWorker.js')
PWA_APP_NAME = 'find a field'
PWA_APP_DESCRIPTION = "Find a field for your sports activities!"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/assets/images/my_app_icon.png',
        'sizes': '192x171'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/assets/images/my_app_icon.png',
        'sizes': '192x171'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/assets/images/splash.png',
        'media': '(max-width: 1024px)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-IE'


AWS_ACCESS_KEY_ID = 'AKIATXSX6RCEHBSAEJB2 '
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'backendcaoimhe'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'eu-west-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERITY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'