# Generated by Django 4.2.7 on 2023-11-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
