# Generated by Django 4.2.7 on 2023-11-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_remove_profile_user_delete_user_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
