# Generated by Django 4.2.8 on 2023-12-30 19:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('OBJECTID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=48, null=True)),
                ('Type', models.CharField(default='Unknown Type', max_length=32, null=True)),
                ('Address', models.CharField(default='Unknown Address', max_length=78, null=True)),
                ('Telephone', models.CharField(default='Unknown Telephone', max_length=13, null=True)),
                ('Web', models.CharField(default='Unknown Web', max_length=34, null=True)),
                ('Streetview', models.CharField(default='Unknown Streetview', max_length=78, null=True)),
                ('WGS84Longi', models.FloatField(default=0.0, null=True)),
                ('WGS4Latitu', models.FloatField(default=0.0, null=True)),
                ('Eircode', models.CharField(default='Unknown Eircode', max_length=7, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
