# Generated by Django 4.2.8 on 2024-01-02 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_sportsfacility_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsfacility',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326),
        ),
    ]
